version: '3.8'

services:
  kong-database:
    image: postgres:13-alpine
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:3.4
    container_name: kong-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    depends_on:
      kong-database:
        condition: service_healthy

  kong:
    image: kong:3.4
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ENFORCE_RBAC: on
      KONG_ADMIN_GUI_AUTH: basic-auth
      KONG_ADMIN_GUI_AUTH_PASSWORD: admin
      KONG_ADMIN_GUI_AUTH_USERNAME: admin
      KONG_SSL: on
      KONG_SSL_CERT: /etc/ssl/certs/barclays-api.crt
      KONG_SSL_CERT_KEY: /etc/ssl/private/barclays-api.key
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
      - "8001:8001"  # Admin API
      - "8002:8002"  # Admin GUI
    volumes:
      - ./ssl:/etc/ssl
      - ./kong.yml:/kong.yml
    depends_on:
      kong-migration:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-dashboard:
    image: pgbi/kong-dashboard:latest
    container_name: kong-dashboard
    environment:
      KONG_DASHBOARD_CONFIG: /etc/kong-dashboard/kong.yml
    ports:
      - "8003:8080"
    volumes:
      - ./kong-dashboard.yml:/etc/kong-dashboard/kong.yml
    depends_on:
      kong:
        condition: service_healthy

volumes:
  kong_data:
    driver: local
